language: php
php:
  - 7.0
  - 7.1
  - 7.2
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
before_script:
  - composer self-update
  - composer update --no-interaction
script:
  - vendor/bin/phpunit --coverage-text
